[versions]
kotlin = "2.0.21"
kotlinx-coroutines = "1.9.0"

[libraries]
assertk = "com.willowtreeapps.assertk:assertk:0.28.1"
auto-service-compiler = { module = "dev.zacsweers.autoservice:auto-service-ksp", version = "1.2.0" }
auto-service-annotations = { module = "com.google.auto.service:auto-service-annotations", version = "1.1.1" }
binary-compatibility-validator-gradle-plugin = { module = "org.jetbrains.kotlinx.binary-compatibility-validator:org.jetbrains.kotlinx.binary-compatibility-validator.gradle.plugin", version = "0.16.3" }
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version = "1.9.20" }
google-ksp = "com.google.devtools.ksp:symbol-processing-gradle-plugin:2.0.20-1.0.25"
junit = { module = "junit:junit", version = "4.13.2" }
kotlin-compile-testing = { module = "dev.zacsweers.kctfork:core", version = "0.5.1" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
mavenPublish-gradle-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version = "0.29.0" }

[plugins]
spotless = { id = "com.diffplug.spotless", version = "6.25.0" }
burst-kotlin = { id = "app.cash.burst.kotlin" }
