[versions]
kotlin = "2.3.0-RC3"
kotlinx-coroutines = "1.10.2"

[libraries]
android-gradlePlugin = "com.android.tools.build:gradle:9.0.0-beta04"
android-gradlePlugin8 = "com.android.tools.build:gradle:8.13.1"
assertk = "com.willowtreeapps.assertk:assertk:0.28.1"
binary-compatibility-validator-gradle-plugin = { module = "org.jetbrains.kotlinx.binary-compatibility-validator:org.jetbrains.kotlinx.binary-compatibility-validator.gradle.plugin", version = "0.18.1" }
junit = { module = "junit:junit", version = "4.13.2" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version = "5.14.1" }
kotlin-compile-testing = { module = "dev.zacsweers.kctfork:core", version = "0.12.0-alpha01" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-metadata-klib = { module = "org.jetbrains.kotlinx:kotlinx-metadata-klib", version = "0.0.6" }
ktlint = "com.pinterest.ktlint:ktlint-cli:1.8.0"
mavenPublish-gradle-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version = "0.35.0" }

[plugins]
buildconfig = { id = "com.github.gmazzo.buildconfig", version = "6.0.6" }
spotless = { id = "com.diffplug.spotless", version = "8.1.0" }
dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }
burst-kotlin = { id = "app.cash.burst.kotlin" }
